### ISSUE TITLE
Case classes / Records encoding

### ISSUE THREAD

**Issue by ahoy-jon** [mandubian/scaledn#2]
The curent implementation choose to encode case classes (records) as pure maps :

``` scala

case class Address(street:String, cp:Int)
case class Person (name:String, age:Int, addr:Address)

Person("toto", 34, Address("chboing", 75009))  =>  
    {"name" "toto", "age" 34, "addr" {"street" "chboing", "cp" 75009 }}
```

But a more classic way would be to use tagged map and to use keywords as keys  :

``` clojure
Person("toto", 34, Address("chboing", 75009))  =>  
    #org.myns/Person {:name "toto", :age 34, 
                      :addr #org.myns/Address {:street "chboing", :cp 75009 }}

;; `org.myns` is the package name of the class Person

```

see record clojure doc : https://clojuredocs.org/clojure.core/defrecord#example_5494d322e4b04e93c519ffaa

**Comment by ahoy-jon** [comment]
In : https://gist.github.com/ahoy-jon/dd555e133228c5037287#file-main-scala

obj, serialise to by default :
```clojure
{"name" "yo", "addr" {"lat" 0.0, "lon" 0.0}}
```

Which might not be good enough compare to : 
```clojure
#yo.HelloEDN/Person {:name "yo", :addr #yo.HelloEDN/Address {:lat 0.0, :lon 0.0}}
```

Would it be possible to implement some strategies ? Like : TaggedRecords, UntaggedSomething ...

**Comment by mandubian** [comment]
Interesting idea.
I think it is possible with a few more implicits... Let's study that!
What would be the default strategy BTW? I chose the dumbest approach with
maps & strings but maybe it's not the best one... a map with keywords could
also be nice for example.

**Comment by ahoy-jon** [comment]
For sure, Keywords should be used instead of Strings : 
* for the performance (you don't create a new keyword instance ideally when you parse, but use the interned value) 
* and for the semantic (keys are not just names as Strings, but a way to 'lookup' and extract part of the information).


As for tags, in Clojure, they are the default for records : 

```clojure
(ns yo.helloedn)

(defrecord Person [name addr])
(defrecord Address [lat lon])

(pr-str (Person. "yo" (Address. 0.0 0.0)))
;=> "#yo.helloedn.Person {:name \"yo\", :addr #yo.helloedn.Address {:lat 0.0, :lon 0.0}}"
```

Even if they are not supported by the included EDN reader !
```clojure

;; Using the standard Clojure reader
(type (read-string  "#yo.helloedn.Person{:name \"yo\", :addr #yo.helloedn.Address{:lat 0.0, :lon 0.0}}"))
;=> yo.helloedn.Person

(require '[clojure.edn :as edn])

(edn/read-string "#yo.helloedn.Person{:name \"yo\", :addr #yo.helloedn.Address{:lat 0.0, :lon 0.0}}")
;=> java.lang.RuntimeException: No reader function for tag yo.helloedn.Address
;=>            EdnReader.java:729 clojure.lang.EdnReader$TaggedReader.readTagged
```
And they don't use slashes (```#yo.helloedn/Person```).


I think [1] the default strategy should be to have a default writer / reader supporting tagged records as Data encoded in this way can be easily decoded (and dispatched) after.

For writing, some advanced strategies could be to : 
* drop tags
* tag transformation (```val f: Named => Named =  _.copy(namespace = NS("yo"))```)

For reading, default should be to throw an exception (or equivalent mechanism) on unregistered tags.

Some other strategies cloud be to : 
* manage unknown tags with TaggedElement, 
* transform tag and dispatch to existing registred tag (```val f: Named => Named =  .... ```)


---
[1] how can we check it's a good idea ? 

---
Are softwares dealing with JSON using "tpe" mecanism (type information inlined (because preserving the existing JSON structure)) to encode the type  ? 
```scala
package greet

case class Yo(greet:String)

toJson(Yo("yo"))
```

```json
{"tpe": "greet.Yo",
 "greet":"yo"}
```

**Comment by mandubian** [comment]
When you say:
> for the performance (you don't create a new keyword instance ideally when you parse, but use the interned value) 

For now, we do not manage an internal dictionary of known keywords while parsing. I think this is one feature to be added in the future.

Nothing prevents us from managing in the EDN reader:

```clojure
(type (read-string  "#yo.helloedn.Person{:name \"yo\" :addr #yo.helloedn.Address{:lat 0.0, :lon 0.0}}"))
```

For Json type encoding, some do it, I'm sure (for RPC for ex) and actually when you want to encode ADT, I believe this is always better to have a type discriminator in your Json.

**Comment by ahoy-jon** [comment]
> Nothing prevents us from managing in the EDN reader:

> ```clojure
(type (read-string  "#yo.helloedn.Person{:name \"yo\" :addr #yo.helloedn.Address{:lat 0.0, :lon 0.0
```

Sure. I have to write more examples. The idea behind is : If you have ~20 case classes to map/read, it should be relatively easy to do.

**Comment by ahoy-jon** [comment]
So I managed to parse + validate this kind of struct  : 

```scala
package yo

import scaledn._
import scaledn.parser._

import macros._
import shapeless._

import play.api.data.mapping._

import validate._

object walk {
   //TODO : Walk in shapeless  ??
   // Post-Order traversal
   def apply (f:Any=> Any, e:Any) : Any = {
   	val p = this.apply(f, (_:Any))
   	e match {
   	   	case l:List[_]   =>  f(l.map(p))
   	   	case l:Vector[_] => f(l.map(p))
   	   	case l:Map[_,_]  => f(l.map(t => (p(t._1),p(t._2))))
   	   	case _ => f(e)
   	   }
   }
}

object HelloEDN  extends App {
  case class Address(lat:Double, lon:Double)
  case class Person (name:String, addr:Address)

  val data = """#yo.helloedn/Person {:name "yo",
     :addr #yo.helloedn/Address {:lat 0.0, :lon 0.0}}"""



  def removetags(e:Any):Any = walk(x => x match {
  	case t:EDNTagged[_]  => removetags(t.value)
  	case _ => x
  }, e)

  def kwToStr(e:Any):Any = walk(x => x match {case EDNKeyword(value) => value.toString 
  	                                          case _ => x}, e)


  println(parseEDN(data).map(removetags).map(kwToStr).map(validateEDN[Person]))
  // Success(Success(Person(yo,Address(0.0,0.0))))

}
```

One utility function could be tagwalk : 
```scala
def tagwalk (f:EDNTagged[_]=> Any, e:Any):Any = walk( x => x match {
   case t:EDNTagged[_] => f(t.copy(value = tagwalk(f,t.value)))
   case _ => x
}, e)

val removetags = tagwalk(_.value, (_:Any))
```
